### ISSUE TITLE
Keep "another one" in the same place for every episode

### ISSUE THREAD

**Issue by alishahimtiaz** [Reid-Luna/CreedFiles#1]
I keep having to scroll down when the length of the text of the current episode is larger than the previous episode, and vice versa.

A solution would be to limit the description of the text, by giving a rough overview of the episode instead of a full synopsis. 

Another solution would be to create a spoiler that extends downwards when clicked revealing the full text. The user can then scroll down accordingly or click "another one"

**Comment by Reid-Luna** [comment]
Fixed.
