### ISSUE TITLE
Empty box on initial page load

### ISSUE THREAD

**Issue by alishahimtiaz** [Reid-Luna/CreedFiles#2]
On page load, an empty box shows, and then the content shows after it loads.
 
To reproduce, open the website in a browser and wait for it to load.

One possible solution would be to add a loading screen with a setTimeout of 1-2 seconds, and then display the content. The "Season", "Episode", and "another one" button should also be removed in the initial page load, and the contents of the box should be a loading screen (a spinning circle perhaps). 

![image](https://user-images.githubusercontent.com/40179229/49318972-aee9e200-f4c8-11e8-9f82-d3032f6b0d88.png)

**Comment by Reid-Luna** [comment]
Thank you, working on fixing this now.

**Comment by Reid-Luna** [comment]
Fixed.
